### ISSUE TITLE
QEMUExtendedKeyEvent not supported

### ISSUE THREAD

**Issue by wentianle** [amitbet/vncproxy#1]
not work;  on keydown or on forcs in  conn close

**Comment by wentianle** [comment]
not suport QEMUExtendedKeyEvent

**Comment by amitbet** [comment]
QEMU extension support was never implemented, it is also not very widely supported in generic vnc servers (tight / ultra / x11vnc  etc.) I would welcome a pull request with a simple implementation, just read the bits from the reader, no processing needed.
https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst#qemu-extended-key-event-message

**Comment by amitbet** [comment]
I added some initial support in the code for the QEMU key messages (see release 1.0.1), but I don't have any QEMU VNC servers to test against, so if you can do some testing / fixing you should be able to use it.

**Comment by wentianle** [comment]
thanks

**Comment by amitbet** [comment]
Should be fixed as I added QemuExtendedKey support.
