### ISSUE TITLE
bad message type, 248 with noVNC 1.1.0

### ISSUE THREAD

**Issue by deanchou** [amitbet/vncproxy#15]
Hi,

Im trying to use noVNC 1.1.0 with vncproxy 1.11 but I got this error:

[Info ] FBS recording is turned off
[Info ] running two listeners: tcp port: :5900, ws url: http://0.0.0.0:5001/
[Error] ClientConn.MainLoop: bad message type, 248
[Warn ] ClientConn.MainLoop: exiting!
[Error] ClientUpdater.Consume (vnc-server-bound, SegmentFullyParsedClientMessage): problem writing to port: write tcp 192.168.0.201:54262->192.168.0.112:5900: use of closed network connection
[Error] IServerConn.Handle: listener consume err write tcp 192.168.0.201:54262->192.168.0.112:5900: use of closed network connection

my cmdline:

proxy -targHost=192.168.0.112 -targPort=5900 -targPass=111111 -tcpPort=5900 -wsPort=5001 -vncPass=111 

rfbproxy works well with this cmdline

./rfbproxy -recFile=./recording.rbs -targHost=192.168.0.112 -targPort=5900 -targPass=111111

Here is my information:
vnc server: tigervnc-1.10.0 (default setting)
noVNC Websockets settings:
    Host: 192.168.0.201
    Port: 5001
    Path:

Am I doing something wrong? Thank you

**Comment by amitbet** [comment]
248 is the Fence command, but I do have support for it in the code...
I think I found the problem - the defaultMessages in the MainLoop didn't contain the ServerFence type.

try this and tell me if it works:
[proxy.zip](https://github.com/amitbet/vncproxy/files/3981922/proxy.zip)

**Comment by amitbet** [comment]
Please tell me if it is fixed, so I can publish a new version with the update.
