### ISSUE TITLE
Problem with noVNC 

### ISSUE THREAD

**Issue by YJesus** [amitbet/vncproxy#4]
Hi,

Im trying to use noVNC 1.0 (the latest) with vncproxy 1.0.2 but I got this error:

[Error] ClientConn.MainLoop: bad message type, 250
[Warn ] ClientConn.MainLoop: exiting!
[Error] ClientUpdater.Consume (vnc-server-bound, SegmentFullyParsedClientMessage): problem writing to port: write tcp 127.0.0.1:34908->127.0.0.1:5900: use of closed network connection
[Error] IServerConn.Handle: listener consume err write tcp 127.0.0.1:34908->127.0.0.1:5900: use of closed network connection

cmdline:

./proxy -recDir=./recordings/ -targHost=127.0.0.1 -targPort=5900 -tcpPort=5001

rfbproxy works well with this cmdline

./rfbproxy --record --server localhost:0 rfb.log

Thank you

**Comment by amitbet** [comment]
When using noVnc you want to open a websocket server, so you should use -wsPort=5001
