### ISSUE TITLE
Recording stops immediately

### ISSUE THREAD

**Issue by yeya** [amitbet/vncproxy#7]
I'm trying to record a session of TightVNC server with the recorder executable.
I don't get any error, and the console is not quitting, it looks like it working but the file is not getting any bigger.
When I'm trying to watch the file with the player executable it shows the first screen and throw error about EOF

I'm using the latest release (1.0.2).
Tested on Tight VNC Server on windows 7 and 10, recorder with ubuntu 16 and windows 10. Same results.

**Comment by amitbet** [comment]
what flags are you using?

**Comment by yeya** [comment]
All required, there is others?

recorder -recDir=./recording.rbs -targHost=192.168.0.100 -targPort=5903
-targPass=@@@@@

**Comment by amitbet** [comment]
try with recDir=./

**Comment by amitbet** [comment]
oh, I see it's the recorder you are using.
It should be recFile there (i'll change it).
turns out that on windows you need to wrap the filename with "", so you should have:
**-recFile="./recording.rbs" -targHost=localhost -targPort=5900 -targPass=12345**

**Comment by amitbet** [comment]
tell me if it worked so I'll close the issue...

**Comment by yeya** [comment]
Sorry, I'll check and update asap

**Comment by yeya** [comment]
`flag provided but not defined: -recFile`

**Comment by amitbet** [comment]
-recDir in the version you are using.. I just uploaded v1.1 with support
for qemu

**Comment by amitbet** [comment]
Closing issue (looks like it was solved)
